### ISSUE TITLE
您好，请问下echarts需要怎么引用mapbox？

### ISSUE THREAD

**Issue by zhou-wjjw** [wlfei0502/mapbox-echarts#1]
我想用mapbox替换百度地图，但是尝试了很多次都没成功，无意间发现您的项目，您能告诉下要用mapbox替换百度地图的关键点在什么地方？谢谢哈

**Comment by wlfei0502** [comment]
主要是替换坐标系统，百度扩展组件里面是用的bmap坐标系统，我是将它的源码改成了这个mapbox-echarts组件，具体引用可以看一下readme。

echarts-gl其实已经集成了mapbox，坐标系统为mapbox3D，只是能做的可视化图表太有限了，主要还是一些三维图表
